/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author HP
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnBuro = new javax.swing.JButton();
        JbtnBuro1 = new javax.swing.JButton();
        JbtnBuro2 = new javax.swing.JButton();
        JbtnBuro3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        JbtnBuro.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro.setText("EDITA INFORMACIÓN");
        JbtnBuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuroActionPerformed(evt);
            }
        });

        JbtnBuro1.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro1.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro1.setText("VERIFICA BURO");
        JbtnBuro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro1ActionPerformed(evt);
            }
        });

        JbtnBuro2.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro2.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro2.setText("ELIMINA REGISTRO");
        JbtnBuro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro2ActionPerformed(evt);
            }
        });

        JbtnBuro3.setBackground(new java.awt.Color(160, 16, 70));
        JbtnBuro3.setForeground(new java.awt.Color(255, 255, 255));
        JbtnBuro3.setText("SOLICITA PRESTAMO");
        JbtnBuro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBuro3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU PRINCIPAL");

        jButton1.setText("CERRAR SESION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbtnBuro2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnBuro1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnBuro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtnBuro3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(JbtnBuro1)
                .addGap(18, 18, 18)
                .addComponent(JbtnBuro)
                .addGap(18, 18, 18)
                .addComponent(JbtnBuro2)
                .addGap(18, 18, 18)
                .addComponent(JbtnBuro3)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnBuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuroActionPerformed
            // Crear una instancia del JFrame de destino
    JFActualiza actualizaFrame = new JFActualiza();
    
    // Hacer visible el JFrame de destino
    actualizaFrame.setVisible(true);
    
    // Opcional: Cerrar o esconder el JFrame actual si lo deseas
    this.dispose(); // Esto cierra la ventana actual
    }//GEN-LAST:event_JbtnBuroActionPerformed

    private void JbtnBuro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro1ActionPerformed
        
    }//GEN-LAST:event_JbtnBuro1ActionPerformed

    private void JbtnBuro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro2ActionPerformed
        // Crear una instancia del JFrame de destino
    JFElimina eliminaFrame = new JFElimina();
    
    // Hacer visible el JFrame de destino
    eliminaFrame.setVisible(true);
    
    // Opcional: Cerrar o esconder la ventana actual
    this.dispose(); // Esto cierra la ventana actual, quítalo si no deseas cerrar esta ventana.
    }//GEN-LAST:event_JbtnBuro2ActionPerformed

    private void JbtnBuro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBuro3ActionPerformed
          // Crear una instancia del JFrame de destino
    JFSolicita_prestamo solicitaPrestamo = new JFSolicita_prestamo();
    
    // Hacer visible el JFrame de destino
    solicitaPrestamo.setVisible(true);
    
    // Opcional: Cerrar o esconder el JFrame actual si lo deseas
    this.dispose(); // Esto cierra la ventana actual
    }//GEN-LAST:event_JbtnBuro3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Cerrar la ventana actual (si es necesario)
        this.dispose(); // Esto cierra la ventana actual

        // Crear una nueva instancia del JFrame principal
        JfPrincipal principal = new JfPrincipal();

        // Hacer visible el JFrame principal
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnBuro;
    private javax.swing.JButton JbtnBuro1;
    private javax.swing.JButton JbtnBuro2;
    private javax.swing.JButton JbtnBuro3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
